import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import ReduxProvider from '../providers/ReduxProvider';
import { AppContextProvider } from "@/context/AppContext";
import Header from "@/components/Header";
import CustomCartBox from "@/components/smallCartBox";
import Footer from "@/components/Footer";
import { ChevronLeft, ChevronRight } from "lucide-react";
import CategoriesSection from "@/components/CategoriesSection";
import SideBar from "@/components/sidebar";
import { Providers } from "./providers";
import GlobalSessionGuard from "@/components/auth/GlobalSessionGuard";

const inter = Inter({
  variable: "--font-inter", // optional
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins", // optional
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const Categories = [
    "Audio",
    "category 2",
    "category 3",
    "category 4",
    "category 5",
    "category 6",
    "category 7",
    "category 8",
    "category 9",
    "category 10",
    "category 11",
    "category 12",
  ]
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} antialiased w-full`}
      >
        <Providers>
          <GlobalSessionGuard />
          <SideBar />
          {/* FIXED HEADER OUTSIDE CONTAINER */}
          <Header />


          <CategoriesSection Categories={Categories} />

          {/* PAGE CONTENT WRAPPER */}
          <div className="pt-[calc(60px+98px)]"> {/* offset for fixed header */}
            <div
              className="
                  max-w-[1440px]
                  px-6
                  mx-auto
                  flex
                  flex-col
                  text-[var(--myTextColorNormal)]
                "
            >

              {children}
            </div>
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
