import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import ReduxProvider from '../providers/ReduxProvider';
import { AppContextProvider } from "@/context/AppContext";
import Header from "@/components/Header";
import CustomCartBox from "@/components/smallCartBox";
import Footer from "@/components/Footer";
import { ChevronLeft, ChevronRight } from "lucide-react";
import CategoriesSection from "@/components/CategoriesSection";
import SideBar from "@/components/sidebar";
import { Providers } from "./providers";
import GlobalSessionGuard from "@/components/auth/GlobalSessionGuard";
import PageContentWrapper from "@/components/PageContentWrapper";
import { getCategories } from "@/utils/utilities";
import SearchModal from "@/components/modals/SearchModal";
import AlertModal from "@/components/modals/AlertModal";
import Script from "next/script";

const inter = Inter({
  variable: "--font-inter", // optional
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins", // optional
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const categories = await getCategories();
  return (
    <html
      lang="en"
      className="dark"
      suppressHydrationWarning
    >
      <head>
        <Script
          id="theme-script"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
            (function() {
              const theme = localStorage.getItem("theme");
              const root = document.documentElement;
              if (theme === "dark") {
                root.classList.add("dark");
              } else if (theme === "light") {
                root.classList.remove("dark");
              } else {
                const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
                root.classList.toggle("dark", prefersDark);
              }
            })();
          `,
          }}
        />
      </head>
      <body
        className={`${inter.variable} ${poppins.variable} antialiased w-full `}
      >
        <Providers>
          <GlobalSessionGuard />
          <SideBar />
          {/* FIXED HEADER OUTSIDE CONTAINER */}
          <Header />
          <CategoriesSection categories={categories} />

          <SearchModal />
          <AlertModal />

          {/* PAGE CONTENT WRAPPER */}
          <PageContentWrapper>
            {children}
          </PageContentWrapper>
          <Footer />

        </Providers>
      </body>
    </html>
  );
}
